name: layout
description: >
  Sample app from "Building Layouts", https://flutter.io/docs/development/ui/layout.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: any
  logger: any
  flame: any

  flutter:
    sdk: flutter
  cupertino_icons: any
  wakelock: ^0.6.1+1
  provider: any
  flame_audio: ^1.0.0
  get_storage: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
  fonts:
    - family: Righteous
      fonts:
        - asset: assets/fonts/Righteous-Regular.ttf

  assets:
    - assets/images/
    - assets/images/peep_life.png
    - assets/audio/
